services:
  service-scheduling:
    build: ./scheduling-service
    restart: always
    environment:
      DB_HOST: scheduling-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: schedulingdb
      DB_PORT: 5432
      USERS_API: http://service-users:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - scheduling-db
      - redis-scheduling
    networks: [AgendaFacil_Scheduling]

  scheduling-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedulingdb
    ports:
      - "5434:5432"
    volumes:
      - scheduling_data:/var/lib/postgresql/data
    networks:
      - AgendaFacil_Scheduling
    
  redis-scheduling:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks: [AgendaFacil_Scheduling]
  
  nginx-scheduling:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - service-scheduling
    networks: [AgendaFacil_Scheduling]

volumes:
  scheduling_data:

networks:
  AgendaFacil_Scheduling:
    driver: bridge