services:
  service-scheduling:
    build: ./scheduling-service
    container_name: service-scheduling
    ports:
      - "3002:3000"
    restart: always
    environment:
      DB_HOST: scheduling-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: schedulingdb
      DB_PORT: 5432
      USERS_API: http://service-users:3000
      REDIS_HOST: redis-scheduling
      REDIS_PORT: 6379
    env_file:
      - scheduling-service/.env
    depends_on:
      scheduling-db:
        condition: service_healthy
    networks:
      - agendafacil_network

  scheduling-db:
    image: postgres:15
    container_name: scheduling-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedulingdb
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schedulingdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - scheduling_data:/var/lib/postgresql/data
    networks:
      - agendafacil_network

  redis-scheduling:
    image: redis:7
    container_name: redis-scheduling
    restart: always
    ports:
      - "6380:6379"
    networks:
      - agendafacil_network
  
  nginx-scheduling:
    image: nginx:alpine
    container_name: nginx-scheduling
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - service-scheduling
    networks:
      - agendafacil_network

volumes:
  scheduling_data:

networks:
  agendafacil_network:
    external: true